name: lidarr
services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:3.1.0
    container_name: lidarr
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
    ports:
      - target: 8686
        published: "8686"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/Media
        target: /media
      - type: bind
        source: /DATA/Download
        target: /downloads
