name: code-server
services:
  code-server:
    image: codercom/code-server:4.141.0
    container_name: code-server
    restart: unless-stopped
    # The bind mounts below are created by Docker as root; code-server runs as
    # uid 1000 by default and could not write to them.
    user: "0:0"
    environment:
      PASSWORD: ${PASSWORD:-}
    ports:
      - target: 8080
        published: "8443"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /root/.config
      - type: bind
        source: /DATA/AppData/$AppID/project
        target: /home/coder/project
