name: searxng
services:
  searxng:
    image: searxng/searxng:2026.10.7-6671d89be
    container_name: searxng
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    ports:
      - target: 8080
        published: "8081"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /etc/searxng
