name: portainer
services:
  portainer:
    image: portainer/portainer-ce:2.45.2
    container_name: portainer
    restart: unless-stopped
    ports:
      - target: 9000
        published: "9001"
        protocol: tcp
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /data
