name: anythingllm
services:
  anythingllm:
    image: mintplexlabs/anythingllm:1.17.0
    container_name: anythingllm
    restart: unless-stopped
    user: "1000:1000"
    cap_add:
      - SYS_ADMIN
    environment:
      STORAGE_DIR: /app/server/storage
    ports:
      - target: 3001
        published: "3001"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/storage
        target: /app/server/storage
